/* Film künyeleri — kaynak: kurucunun sağladığı portfolyo dosyaları.
 * credit_basis: kullanıcı beyanı (bağımsız doğrulama yapılmadı).
 * Katkı hem ses tasarımı hem müzik olarak yapıldığı için ikisi birlikte yazılıyor.
 * Görseli olmayan kayıtlar standart bir SVG kapakla listelenir.
 */
export default [
  {
    "slug": "tesekkurler-supermen",
    "baslik": "Teşekkürler Süpermen",
    "tur": "Kısa Film",
    "turEN": "Short Film",
    "yil": 2020,
    "yonetmen": "Ozan Sertdemir",
    "vizyon": null,
    "aciklama": "Market çalışanı Hayati, Evren’i kurtarmasının ardından beklenmedik biçimde bir kahramana dönüşür. Bu yeni imaj, reklam dünyasının ilgisiyle başka bir boyut kazanır. Ozan Sertdemir’in kara komedisi, sıradan bir insanın kahraman olarak sunulmasının yarattığı dönüşümü anlatır.",
    "gorsel": null,
    "taslak": true
  },
  {
    "slug": "gece-gelen",
    "baslik": "Gece Gelen: Cin Bebek",
    "tur": "Sinema Filmi",
    "turEN": "Feature Film",
    "yil": 2019,
    "yonetmen": "Bülent Aydoslu",
    "vizyon": "2020",
    "aciklama": "Doğa’nın köydeki yaşamı, kendisine musallat olan doğaüstü varlıkla birlikte bir kâbusa dönüşür. İçinde bulunduğu durumdan kurtulmak için aradığı çözüm, onu yeni bir anlaşmaya sürükler. Bülent Aydoslu’nun korku filmi, bu çıkış arayışını izler.",
    "gorsel": "/assets/img/portfolyo/gece-gelen.jpg",
    "taslak": true
  },
  {
    "slug": "kacis",
    "baslik": "Kaçış",
    "tur": "Kısa Film",
    "turEN": "Short Film",
    "yil": 2019,
    "yonetmen": null,
    "vizyon": null,
    "aciklama": "Kaçış, 2019 yılı müzik çalışmalarımız arasında yer alan bir kısa film projesi.",
    "gorsel": null,
    "taslak": true
  },
  {
    "slug": "maraton",
    "baslik": "Maraton",
    "tur": "Kısa Film",
    "turEN": "Short Film",
    "yil": 2019,
    "yonetmen": "Alper Akdeniz",
    "vizyon": null,
    "aciklama": "Teknolojinin insan yaşamıyla kurduğu ilişki, kesintisiz bir çekimde anlatılıyor. Alper Akdeniz’in İzmir’de çektiği Maraton, kısa süresine yoğun bir görsel anlatı sığdıran deneysel bir film. Gündelik hayatın akışı ve teknolojinin etkisi aynı kadrajda buluşuyor.",
    "gorsel": "/assets/img/portfolyo/maraton.jpg",
    "taslak": false
  },
  {
    "slug": "sauseerig",
    "baslik": "Sauseerig",
    "tur": "Tanıtım Filmi",
    "turEN": "Promotional Film",
    "yil": 2019,
    "yonetmen": null,
    "vizyon": null,
    "aciklama": "Sauseerig, 2019 yılı müzik çalışmalarımız arasında yer alan bir tanıtım filmi projesi.",
    "gorsel": null,
    "taslak": true
  },
  {
    "slug": "tavsan",
    "baslik": "Tavşan",
    "tur": "Kısa Film",
    "turEN": "Short Film",
    "yil": 2019,
    "yonetmen": "Abdullah Rıdvan Can",
    "vizyon": null,
    "aciklama": "Başarılı atlet Zeynep’ten, yaklaşan yarışta diğer koşuculara tempo sağlayan “tavşan atlet” rolünü üstlenmesi istenir. Abdullah Rıdvan Can’ın kısa filmi, spor dünyasındaki bu görevi hikâyesinin merkezine yerleştirir ve yarışa Zeynep’in bulunduğu yerden bakar.",
    "gorsel": "/assets/img/portfolyo/tavsan.jpg",
    "taslak": false
  },
  {
    "slug": "ismetse-olur",
    "baslik": "İsmetse Olur",
    "tur": "Sinema Filmi",
    "turEN": "Feature Film",
    "yil": 2019,
    "yonetmen": "Umut Kaya",
    "vizyon": "2022",
    "aciklama": "Kısmetli köyüne gelen dolandırıcılar, köylülere bir bukalemun çiftliği kurmayı önerir. Köyün saf delikanlısı İsmet’in varlığı ise hesaplarını bozar. Umut Kaya’nın komedisi, kolay kazanç vaadini köy yaşamı ve beklenmedik karşılaşmalar üzerinden anlatır.",
    "gorsel": "/assets/img/portfolyo/ismetse-olur.jpg",
    "taslak": false
  },
  {
    "slug": "bekci",
    "baslik": "Bekçi",
    "tur": "Sinema Filmi",
    "turEN": "Feature Film",
    "yil": 2018,
    "yonetmen": "Durmuş Akbulut",
    "vizyon": "2019",
    "aciklama": "Mezarlıkta gece bekçiliği yapan Salih’in düzeni, karşılaştığı kişiler ve gördüğü rüyalarla değişmeye başlar. Gerçekle düş arasındaki sınır belirsizleşirken gece, başka bir anlam kazanır. Durmuş Akbulut’un filmi, gündelik bir görevin içinden tekinsiz bir dünya kurar.",
    "gorsel": "/assets/img/portfolyo/bekci.jpg",
    "taslak": true
  },
  {
    "slug": "ecinni",
    "baslik": "Ecinni",
    "tur": "Sinema Filmi",
    "turEN": "Feature Film",
    "yil": 2018,
    "yonetmen": "Mehmet Sağlam",
    "vizyon": "2018",
    "aciklama": "Çocukluğunda kardeşini kaybeden Kadir, arkadaşlarıyla birlikte eski bir köyde belgesel çekmek için yola çıkar. Yolculuk sırasında başlayan tuhaf olaylar, geçmişiyle kurduğu bağı yeniden açığa çıkarır. Mehmet Sağlam’ın korku filmi, bir çekim ekibinin yolculuğunu doğaüstü bir karşılaşmaya dönüştürür.",
    "gorsel": "/assets/img/portfolyo/ecinni.jpg",
    "taslak": false
  },
  {
    "slug": "firtina-murat",
    "baslik": "Fırtına Murat — En Uzun Gece",
    "tur": "Sinema Filmi",
    "turEN": "Feature Film",
    "yil": 2018,
    "yonetmen": "Orhan Kılıç",
    "vizyon": "2019",
    "aciklama": "Bir kamyonda bulunan ölü göçmenler, Komiser Murat’ı organ ticaretine uzanan bir soruşturmanın içine çeker. Murat, suçun izini sürerken adalet ve hukuk arasında zor kararlarla karşılaşır. Orhan Kılıç’ın polisiye filmi, En Uzun Gece adıyla da biliniyor.",
    "gorsel": "/assets/img/portfolyo/firtina-murat.jpg",
    "taslak": false
  },
  {
    "slug": "kestik",
    "baslik": "Kestik",
    "tur": "Kısa Film",
    "turEN": "Short Film",
    "yil": 2018,
    "yonetmen": null,
    "vizyon": null,
    "aciklama": "Kestik, 2018 yılı müzik çalışmalarımız arasında yer alan bir kısa film projesi.",
    "gorsel": null,
    "taslak": true
  },
  {
    "slug": "kimliklerim-semtim",
    "baslik": "Kimliklerim, Semtim",
    "tur": "Belgesel",
    "turEN": "Documentary",
    "yil": 2018,
    "yonetmen": null,
    "vizyon": null,
    "aciklama": "Kimliklerim, Semtim, 2018 yılı müzik çalışmalarımız arasında yer alan bir belgesel projesi.",
    "gorsel": null,
    "taslak": true
  },
  {
    "slug": "kotu-film",
    "baslik": "Kötü Film",
    "tur": "Kısa Film",
    "turEN": "Short Film",
    "yil": 2018,
    "yonetmen": null,
    "vizyon": null,
    "aciklama": "Kötü Film, 2018 yılı müzik çalışmalarımız arasında yer alan bir kısa film projesi.",
    "gorsel": null,
    "taslak": true
  },
  {
    "slug": "sonsuz-zaman-icinde",
    "baslik": "Sonsuz Zaman İçinde",
    "tur": "Kısa Film",
    "turEN": "Short Film",
    "yil": 2018,
    "yonetmen": "Emre Doğan",
    "vizyon": null,
    "aciklama": "Küçük bir kız, doğum için şehre giden annesini büyükannesi ve büyükbabasıyla bekler. Yeni doğacak kardeşinin sağlığıyla kendi davranışları arasında kurulan bağ, onu ağır bir sorumluluk duygusuyla karşı karşıya bırakır. Emre Doğan’ın filmi, çocukluk deneyimini aile ve inanışlar üzerinden anlatır.",
    "gorsel": "/assets/img/portfolyo/sonsuz-zaman-icinde.jpg",
    "taslak": true
  },
  {
    "slug": "varlik",
    "baslik": "Varlık",
    "tur": "Kısa Film",
    "turEN": "Short Film",
    "yil": 2018,
    "yonetmen": null,
    "vizyon": null,
    "aciklama": "Varlık, 2018 yılı müzik çalışmalarımız arasında yer alan bir kısa film projesi.",
    "gorsel": null,
    "taslak": true
  },
  {
    "slug": "dal",
    "baslik": "Dal",
    "tur": "Belgesel",
    "turEN": "Documentary",
    "yil": 2017,
    "yonetmen": null,
    "vizyon": null,
    "aciklama": "Dal, 2017 yılı müzik çalışmalarımız arasında yer alan bir belgesel projesi.",
    "gorsel": null,
    "taslak": true
  },
  {
    "slug": "kader",
    "baslik": "Kader",
    "tur": "Uzun Metraj",
    "turEN": "Feature",
    "yil": 2017,
    "yonetmen": null,
    "vizyon": null,
    "aciklama": "Kader, 2017 yılı müzik çalışmalarımız arasında yer alan bir uzun metraj projesi.",
    "gorsel": null,
    "taslak": true
  },
  {
    "slug": "noradrenalin",
    "baslik": "Noradrenalin",
    "tur": "Kısa Film",
    "turEN": "Short Film",
    "yil": 2017,
    "yonetmen": "Antonio Özçevik",
    "vizyon": null,
    "aciklama": "Aşkın yasaklandığı 2030 yılında Eşref, hasta annesine bakarken çevresindeki toplumsal çözülmeyle de yüzleşir. Noradrenalin, kişisel bir bakım hikâyesini karanlık bir gelecek tasavvuruyla buluşturan distopik bir kısa film.",
    "gorsel": "/assets/img/portfolyo/noradrenalin.jpg",
    "taslak": false
  },
  {
    "slug": "son-aksam-yemegi",
    "baslik": "Son Akşam Yemeği",
    "tur": "Kısa Film",
    "turEN": "Short Film",
    "yil": 2017,
    "yonetmen": "Hatice Aşkın",
    "vizyon": null,
    "aciklama": "Şef Levent, arkadaşı Kurtuluş’un sıra dışı iş fikriyle karşılaşır: Acı çeken insanlara son yemeklerini sunan bir şirket kurmak. Hatice Aşkın’ın kısa filmi, bu teklif üzerinden insan yaşamına ve acıya ilişkin rahatsız edici bir soruyu gündeme getirir.",
    "gorsel": null,
    "taslak": true
  },
  {
    "slug": "umut-avcilari",
    "baslik": "Umut Avcıları",
    "tur": "Sinema Filmi",
    "turEN": "Feature Film",
    "yil": 2017,
    "yonetmen": "İlker Çavga",
    "vizyon": "2018",
    "aciklama": "Anıtkaya’da yaşayan dört arkadaş, define bulma umuduyla bir maceraya atılır. Paris’ten köye dönen bir iş insanının gelişiyle yolları kesişir; hayaller ve beklenmedik olaylar birbirine karışır. Umut Avcıları, köy yaşamını bir define arayışının çevresinde anlatan bir komedi.",
    "gorsel": "/assets/img/portfolyo/umut-avcilari.jpg",
    "taslak": false
  },
  {
    "slug": "bukle",
    "baslik": "Bukle",
    "tur": "Kamu Spotu",
    "turEN": "Public Service Film",
    "yil": 2016,
    "yonetmen": "Ömer Gümüşer",
    "vizyon": null,
    "aciklama": "LÖSEV için hazırlanan Bukle, lösemi konusunda farkındalık yaratmayı amaçlayan bir kamu spotu. Ömer Gümüşer’in kısa yapımı, toplumsal bir meseleyi sinema aracılığıyla görünür kılıyor.",
    "gorsel": null,
    "taslak": true
  },
  {
    "slug": "aya",
    "baslik": "Aya",
    "tur": "Kısa Film",
    "turEN": "Short Film",
    "yil": 2015,
    "yonetmen": null,
    "vizyon": null,
    "aciklama": "Aya, 2015 yılı müzik çalışmalarımız arasında yer alan bir kısa film projesi.",
    "gorsel": null,
    "taslak": true
  },
  {
    "slug": "perdenin-ardindan",
    "baslik": "Perdenin Ardından",
    "tur": "Kısa Film",
    "turEN": "Short Film",
    "yil": 2013,
    "yonetmen": null,
    "vizyon": null,
    "aciklama": "Perdenin Ardından, 2013 yılı müzik çalışmalarımız arasında yer alan bir kısa film projesi.",
    "gorsel": null,
    "taslak": true
  },
  {
    "slug": "ecinni-2",
    "baslik": "Ecinni 2: Tılsımlı Mezar",
    "tur": "Sinema Filmi",
    "turEN": "Feature Film",
    "yil": null,
    "yonetmen": "Mehmet Sağlam",
    "vizyon": "2019",
    "aciklama": "Yılmaz, Sinan, Eda ve Sema, eski bir rahibenin mezarındaki bileziğin peşine düşer. Mezarın açılmasıyla birlikte tılsımlar bozulur ve arayışları korkutucu olaylara sürüklenir. Ecinni serisinin ikinci filmi, ilk filmin köyüne yeni bir hikâyeyle geri döner.",
    "gorsel": "/assets/img/portfolyo/ecinni-2.jpg",
    "taslak": false
  },
  {
    "slug": "ecinni-3",
    "baslik": "Ecinni 3: Issız Çığlık",
    "tur": "Sinema Filmi",
    "turEN": "Feature Film",
    "yil": null,
    "yonetmen": "Mehmet Sağlam",
    "vizyon": "2021",
    "aciklama": "Zeynep’in gördüğü gizemli görüntüler, ailesinin yaşamını etkileyen bir dizi olayın başlangıcı olur. Küçük kardeşi Elif’in kaybolmasıyla birlikte bilinmeyenin peşindeki arayış derinleşir. Ecinni serisinin üçüncü filmi, aile bağlarını doğaüstü bir tehdidin içinde ele alır.",
    "gorsel": "/assets/img/portfolyo/ecinni-3.jpg",
    "taslak": false
  },
  {
    "slug": "ege-gunesi",
    "baslik": "Ege Güneşi",
    "tur": "Belgesel",
    "turEN": "Documentary",
    "yil": null,
    "yonetmen": "Ömer Gümüşer",
    "vizyon": null,
    "aciklama": "İzmir’deki bir lunaparkın çalışanları, eski dönme dolabın sökülmesi ve değişen çalışma koşullarıyla birlikte belirsiz bir döneme girer. Ömer Gümüşer’in belgeseli, eğlencenin arkasındaki emeğe yaklaşır; iş, geçim ve gelecek kaygısını çalışanların gündelik yaşamları içinde takip eder.",
    "gorsel": "/assets/img/portfolyo/ege-gunesi.jpg",
    "taslak": false
  }
];
