/* Spotify künyeleri — kaynak: her parçanın Spotify sayfasındaki
 * "Katkıda bulunanlar" penceresi (kontrol tarihi 2026-09-06).
 *
 * kategori:
 *   "muzik" — künyede kurucunun adı geçiyor (söz/beste/aranje ya da prodüksiyon).
 *             Hangi rolle geçtiği `roller` alanında duruyor.
 *   "miks"  — künyede adı hiç geçmiyor. Spotify künyeleri miks/mastering
 *             mühendisini çoğu kayıtta listelemediği için bu işler stüdyonun
 *             kendi kaydına dayanıyor; sayfada bu not açıkça yazılı.
 *
 * appleUrl bilerek null: Apple Music linkleri geldiğinde yalnızca bu alan dolar.
 */
export default [
  {
    "slug": "yuruyorum-dikenlerin-ustunde",
    "baslik": "Yürüyorum Dikenlerin Üstünde",
    "sanatcilar": "Can Kiremitci, Furkan Kızılay, Aytaç Şahin, Muharrem Salcı, Eda Akman, Kaan Cengiz, Asena Bayat, Nilay, Emre Kayacan, Levent Batu, ufuk sinkil, Özgür Can Öney, Hazal Filiz Küçükköse, Böyleyken Böyle, Aslı Bekiroğlu, Yiğit Seferoğlu, Aşarhan, Egemen Akkol, Özkan Sağın, Ertunç, Selin İrman, DOU, Beste Dağdelen, Arda İrman, Selin Baycan, Mesut Çakır",
    "album": "Yürüyorum Dikenlerin Üstünde",
    "albumUrl": "https://open.spotify.com/album/28LvtD0hc6aWUFegfnAqOm",
    "tur": "Single",
    "tarih": "2026-04-03",
    "sure": "5:11",
    "spotifyUrl": "https://open.spotify.com/track/4DITSSPpEvVIbqckXbbElm",
    "spotifyId": "4DITSSPpEvVIbqckXbbElm",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273515c0e71b09d04d27c83cc79",
    "sozBeste": "Can Kiremitci: Besteci; Hasan Kaplan: Yazar",
    "produksiyon": "Can Kiremitci: Prodüktör; Burak Ataş: Ses Mühendisi",
    "digerKunye": null,
    "kunyeKaynagi": "PIST",
    "roller": [
      "Besteci",
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "kalbim-sana-emanet",
    "baslik": "Kalbim Sana Emanet",
    "sanatcilar": "Ayda",
    "album": "Kalbim Sana Emanet",
    "albumUrl": "https://open.spotify.com/album/6DAPqLIc9nG8WnlQY6YZV9",
    "tur": "Single",
    "tarih": "2025-08-22",
    "sure": "2:11",
    "spotifyUrl": "https://open.spotify.com/track/0Pdl3rgS5g4LdRRyhyPFNR",
    "spotifyId": "0Pdl3rgS5g4LdRRyhyPFNR",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273dbe8fc9352aafa0e120d4865",
    "sozBeste": "Unal Tuzun: Besteci, Söz Yazarı",
    "produksiyon": "Yiğitcan Kiremitci: Mix Mühendisi, Kayıt Mühendisi, Mastering Mühendisi, Prodüktör",
    "digerKunye": "Ayda: Geri Vokaller, Vokal",
    "kunyeKaynagi": "Ayda",
    "roller": [
      "Mix Mühendisi",
      "Kayıt Mühendisi",
      "Mastering Mühendisi",
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "arsizim",
    "baslik": "Arsızım",
    "sanatcilar": "İVEN",
    "album": "Arsızım",
    "albumUrl": "https://open.spotify.com/album/13VQWnzwscrT2aEfdhalSF",
    "tur": "Single",
    "tarih": "2025-04-18",
    "sure": "2:54",
    "spotifyUrl": "https://open.spotify.com/track/6JHBLX3nbUPrZyWnHjqVYp",
    "spotifyId": "6JHBLX3nbUPrZyWnHjqVYp",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b27338de0b6235b489cd89e1ad9a",
    "sozBeste": "İBrahim İVen: Besteci, Söz Yazarı",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "Pist",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "paramparca",
    "baslik": "Paramparça",
    "sanatcilar": "Cemre Kıralioğlu",
    "album": "Paramparça",
    "albumUrl": "https://open.spotify.com/album/6d28VOoI5di21OnA6jr86s",
    "tur": "Single",
    "tarih": "2025-03-07",
    "sure": "2:45",
    "spotifyUrl": "https://open.spotify.com/track/24Yo7z0ws6MXN5BsktX8wS",
    "spotifyId": "24Yo7z0ws6MXN5BsktX8wS",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273ee7b5f2fc97a8e1bde71b72c",
    "sozBeste": "Cemre Kıralioğlu: Besteci, Söz Yazarı",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "Pist",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "burden",
    "baslik": "Burden",
    "sanatcilar": "Samar in Silence",
    "album": "This is Not Normal",
    "albumUrl": "https://open.spotify.com/album/5jaeLayulolQjBtluIRgqY",
    "tur": "Album",
    "tarih": "2025-03-01",
    "sure": "4:22",
    "spotifyUrl": "https://open.spotify.com/track/23ntfobihVmq6oJIFsdO0g",
    "spotifyId": "23ntfobihVmq6oJIFsdO0g",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273412f1e3ef61c72881746e783",
    "sozBeste": "Samar Halim: Söz Yazarı, Besteci",
    "produksiyon": "Samar Halim: Stüdyo Prodüktörü, Stüdyo Personeli",
    "digerKunye": null,
    "kunyeKaynagi": "Samar in Silence",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "uzuldugum-zamanlarda",
    "baslik": "Üzüldüğüm Zamanlarda",
    "sanatcilar": "Böyleyken Böyle",
    "album": "Üzüldüğüm Zamanlarda",
    "albumUrl": "https://open.spotify.com/album/4odY0LnC5NAf2fc8kSCjlH",
    "tur": "Single",
    "tarih": "2025-02-28",
    "sure": "3:07",
    "spotifyUrl": "https://open.spotify.com/track/12lZ76ibE7cuD2kIR8D89i",
    "spotifyId": "12lZ76ibE7cuD2kIR8D89i",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b27309bbed7d5bb8e8d7c90f070e",
    "sozBeste": "Mustafa Kır: Besteci, Söz Yazarı",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "Bayhan Prodüksiyon",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "citlembik",
    "baslik": "ÇİTLEMBİK",
    "sanatcilar": "İKOO",
    "album": "ÇİTLEMBİK",
    "albumUrl": "https://open.spotify.com/album/4smsO3M9DAw0K5XqZBZKhE",
    "tur": "Single",
    "tarih": "2025-02-21",
    "sure": "2:16",
    "spotifyUrl": "https://open.spotify.com/track/6nMwLPG3rC5ce8xo2lpgIG",
    "spotifyId": "6nMwLPG3rC5ce8xo2lpgIG",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b27309627728ae541d8802adf3ef",
    "sozBeste": "İLker Aydın: Besteci, Söz Yazarı",
    "produksiyon": "Can Kiremitci: Prodüktör; Doğukan Kara: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Pist",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "bendeki-sen",
    "baslik": "Bendeki sen",
    "sanatcilar": "İVEN",
    "album": "Bendeki sen",
    "albumUrl": "https://open.spotify.com/album/7iDLh9KVyqSNmfibCB6Npr",
    "tur": "Single",
    "tarih": "2025-01-31",
    "sure": "2:58",
    "spotifyUrl": "https://open.spotify.com/track/3OyyolJWLu6bejynQnjFYN",
    "spotifyId": "3OyyolJWLu6bejynQnjFYN",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2731d72746a3606ff758f1578a9",
    "sozBeste": "İBrahim İVen: Besteci, Söz Yazarı",
    "produksiyon": "Can Kiremitci: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Pist",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "gelincik",
    "baslik": "Gelincik",
    "sanatcilar": "Cemre Kıralioğlu",
    "album": "Gelincik",
    "albumUrl": "https://open.spotify.com/album/12BbA2cwu1uQYi5cl6giWc",
    "tur": "Single",
    "tarih": "2024-12-20",
    "sure": "3:17",
    "spotifyUrl": "https://open.spotify.com/track/59a5SVlwZmu4eM1884qUmD",
    "spotifyId": "59a5SVlwZmu4eM1884qUmD",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273ad93e4f15ea3f4fabf013622",
    "sozBeste": "Cemre Kıralioğlu: Besteci, Söz Yazarı",
    "produksiyon": "Can Kiremitci: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Pist",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "yok-yere",
    "baslik": "Yok Yere",
    "sanatcilar": "Ayda",
    "album": "Yok Yere",
    "albumUrl": "https://open.spotify.com/album/12JLa5qeQSs3JtPPArrmC1",
    "tur": "Single",
    "tarih": "2024-11-08",
    "sure": "2:36",
    "spotifyUrl": "https://open.spotify.com/track/5QocrcPDrYHOLKsNaGYW98",
    "spotifyId": "5QocrcPDrYHOLKsNaGYW98",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273b03011d28a68bff31e7a2be1",
    "sozBeste": "Cemre Kıralioğlu: Besteci, Söz Yazarı; Shahin Yarali: Besteci, Söz Yazarı",
    "produksiyon": "Yiğitcan Kiremitci: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Ayda",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "ben-yanildim",
    "baslik": "Ben Yanıldım",
    "sanatcilar": "Cemre Kıralioğlu",
    "album": "Ben Yanıldım",
    "albumUrl": "https://open.spotify.com/album/4eEAnRsftmuXuhFWkm9tdr",
    "tur": "Single",
    "tarih": "2024-11-01",
    "sure": "2:14",
    "spotifyUrl": "https://open.spotify.com/track/3j8M5ON91qpVuvyqiM5yl5",
    "spotifyId": "3j8M5ON91qpVuvyqiM5yl5",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273206a00f7d67c334bdca81d00",
    "sozBeste": "Cemre Kıralioğlu: Besteci, Söz Yazarı, Aranjör; Can Kiremitci: Aranjör; Engin Hızarcı: Aranjör",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "Pist",
    "roller": [
      "Aranjör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "zehirlendim",
    "baslik": "Zehirlendim",
    "sanatcilar": "Böyleyken Böyle",
    "album": "Zehirlendim",
    "albumUrl": "https://open.spotify.com/album/3gkdSN75dpv7SHkRvPTd52",
    "tur": "Single",
    "tarih": "2024-10-04",
    "sure": "2:19",
    "spotifyUrl": "https://open.spotify.com/track/373fTOuW1GBxQZR3sMHxjX",
    "spotifyId": "373fTOuW1GBxQZR3sMHxjX",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b27337545bf0b96f79b6c88adc8a",
    "sozBeste": "Mustafa Kır: Besteci, Söz Yazarı; Can Kiremitci: Aranjör",
    "produksiyon": "Can Kiremitci: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Bayhan Prodüksiyon",
    "roller": [
      "Aranjör",
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "holly",
    "baslik": "holly",
    "sanatcilar": "zei",
    "album": "holly",
    "albumUrl": "https://open.spotify.com/album/6qf5Zi3FjD1W1jAZEzM7IT",
    "tur": "Single",
    "tarih": "2024-10-04",
    "sure": "2:14",
    "spotifyUrl": "https://open.spotify.com/track/0UqmgJ47W4WU3xw8iLAyib",
    "spotifyId": "0UqmgJ47W4WU3xw8iLAyib",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273d5ee41f8caee12549322fc9c",
    "sozBeste": "zei: Besteci",
    "produksiyon": "Can Kiremitci: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Boomers Records",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "olay",
    "baslik": "Olay",
    "sanatcilar": "Cemre Kıralioğlu",
    "album": "Olay",
    "albumUrl": "https://open.spotify.com/album/424oUbRS7TPlf7g7WKdd2A",
    "tur": "Single",
    "tarih": "2024-09-13",
    "sure": "2:17",
    "spotifyUrl": "https://open.spotify.com/track/6mqkIxWERlGJ7AMjS1nXI6",
    "spotifyId": "6mqkIxWERlGJ7AMjS1nXI6",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2736236540f7bdfa8f6fa639889",
    "sozBeste": "Cemre Kıralioğlu: Besteci, Söz Yazarı",
    "produksiyon": "Can Kiremitci: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Pist",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "cok-sevdim",
    "baslik": "Çok Sevdim",
    "sanatcilar": "Böyleyken Böyle",
    "album": "Çok Sevdim",
    "albumUrl": "https://open.spotify.com/album/5eyMBgyFcS8Ji46F6Kg5RH",
    "tur": "Single",
    "tarih": "2024-09-06",
    "sure": "2:54",
    "spotifyUrl": "https://open.spotify.com/track/13n0yHb4lidng6qEkLASaP",
    "spotifyId": "13n0yHb4lidng6qEkLASaP",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273aa56aa57d0447eae6a4d6a08",
    "sozBeste": "Mustafa Kır: Besteci, Söz Yazarı; Can Kiremitci: Aranjör",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "Bayhan Prodüksiyon",
    "roller": [
      "Aranjör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "sen-olmadan",
    "baslik": "Sen Olmadan",
    "sanatcilar": "MURAT YILDIZ",
    "album": "Sen Olmadan",
    "albumUrl": "https://open.spotify.com/album/6TlWkkLRX0vvZhn62J2skn",
    "tur": "Single",
    "tarih": "2024-08-09",
    "sure": "2:53",
    "spotifyUrl": "https://open.spotify.com/track/2GH9hqWAyoEe0sSbO2TzjW",
    "spotifyId": "2GH9hqWAyoEe0sSbO2TzjW",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b27349c631e6a0027855e5b47d96",
    "sozBeste": "MURAT YILDIZ: Besteci, Söz Yazarı",
    "produksiyon": "MURAT YILDIZ: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "SOYKAN MÜZİK",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "lucifer",
    "baslik": "lucifer",
    "sanatcilar": "zei",
    "album": "lucifer",
    "albumUrl": "https://open.spotify.com/album/4ezUpkwpzPl1x1XP7fLBbo",
    "tur": "Single",
    "tarih": "2024-07-26",
    "sure": "2:38",
    "spotifyUrl": "https://open.spotify.com/track/43cLvPWSAX7RadiOB6ZaDC",
    "spotifyId": "43cLvPWSAX7RadiOB6ZaDC",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273261257759fc6477bf4d2259d",
    "sozBeste": "zei: Besteci",
    "produksiyon": "Can Kiremitci: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Boomers Records",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "zehirlenebilir-hayatim",
    "baslik": "Zehirlenebilir Hayatım",
    "sanatcilar": "Böyleyken Böyle",
    "album": "Zehirlenebilir Hayatım",
    "albumUrl": "https://open.spotify.com/album/56V62z7z0Y6GlessYeIpDU",
    "tur": "Single",
    "tarih": "2024-05-10",
    "sure": "2:43",
    "spotifyUrl": "https://open.spotify.com/track/238wbgbcWPejxUdxqKfKRS",
    "spotifyId": "238wbgbcWPejxUdxqKfKRS",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2737948ad8bb7bffd3974623ffa",
    "sozBeste": "Mustafa Kır: Besteci, Söz Yazarı; Can Kiremitci: Aranjör",
    "produksiyon": "Mustafa Kır: Prodüktör; Can Kiremitci: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Aranjör",
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "still-hung-up",
    "baslik": "Still Hung Up",
    "sanatcilar": "Samar in Silence",
    "album": "Delusional",
    "albumUrl": "https://open.spotify.com/album/3OwC6rp9Kxs0VX5MhuqDDF",
    "tur": "Album",
    "tarih": "2024-03-01",
    "sure": "4:06",
    "spotifyUrl": "https://open.spotify.com/track/1iVXmRfjHBp88gcCUl3D4c",
    "spotifyId": "1iVXmRfjHBp88gcCUl3D4c",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273a97ec36e8d3332e0f7cbf4e0",
    "sozBeste": "Samar Halim: Söz Yazarı, Besteci",
    "produksiyon": "Samar Halim: Stüdyo Prodüktörü",
    "digerKunye": null,
    "kunyeKaynagi": "Samar in Silence",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "oh-well",
    "baslik": "Oh Well",
    "sanatcilar": "Samar in Silence",
    "album": "Delusional",
    "albumUrl": "https://open.spotify.com/album/3OwC6rp9Kxs0VX5MhuqDDF",
    "tur": "Album",
    "tarih": "2024-03-01",
    "sure": "4:14",
    "spotifyUrl": "https://open.spotify.com/track/1C1ex2PyxgHNChpVwKEIud",
    "spotifyId": "1C1ex2PyxgHNChpVwKEIud",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273a97ec36e8d3332e0f7cbf4e0",
    "sozBeste": "Samar Halim: Söz Yazarı, Besteci",
    "produksiyon": "Samar Halim: Stüdyo Prodüktörü",
    "digerKunye": null,
    "kunyeKaynagi": "Samar in Silence",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "belki-bi-gun-anlarsin",
    "baslik": "Belki Bi' Gün Anlarsın",
    "sanatcilar": "Böyleyken Böyle",
    "album": "Belki Bi' Gün Anlarsın",
    "albumUrl": "https://open.spotify.com/album/4TjIITyVEoaYup0JFmNMjg",
    "tur": "Single",
    "tarih": "2024-02-23",
    "sure": "2:25",
    "spotifyUrl": "https://open.spotify.com/track/0ddXQ4eNqVOr1YacLki5Xa",
    "spotifyId": "0ddXQ4eNqVOr1YacLki5Xa",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2730ec85e0f1c362ee96c8f4834",
    "sozBeste": "Mustafa Kır: Besteci, Söz Yazarı, Aranjör; Can Kiremitci: Aranjör",
    "produksiyon": "Mustafa Kır: Prodüktör; Can Kiremitci: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Aranjör",
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "biz-seninle",
    "baslik": "Biz Seninle",
    "sanatcilar": "İVEN",
    "album": "Biz Seninle",
    "albumUrl": "https://open.spotify.com/album/4oEt7UM8vyMHj3ksKP2o9k",
    "tur": "Single",
    "tarih": "2024-01-26",
    "sure": "4:12",
    "spotifyUrl": "https://open.spotify.com/track/2D6QNdWOXLi9HB6Kbp0iNz",
    "spotifyId": "2D6QNdWOXLi9HB6Kbp0iNz",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2737662cca52acb3f645788f215",
    "sozBeste": "İbrahim İven: Besteci, Söz Yazarı, Aranjör; Yiğitcan Kiremitçi: Aranjör",
    "produksiyon": "Yiğitcan Kiremitçi: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Pink Limo Entertainment",
    "roller": [
      "Aranjör",
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "karanlik-sokaklar",
    "baslik": "Karanlık Sokaklar",
    "sanatcilar": "İVEN",
    "album": "Karanlık Sokaklar",
    "albumUrl": "https://open.spotify.com/album/3koRLdewjaAcimQ0CDSLhJ",
    "tur": "Single",
    "tarih": "2023-11-17",
    "sure": "3:23",
    "spotifyUrl": "https://open.spotify.com/track/6ZtjAYRUacYINAf1aPFvlj",
    "spotifyId": "6ZtjAYRUacYINAf1aPFvlj",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273de968ee56db78d84782da2d7",
    "sozBeste": "İbrahim İven: Besteci, Söz Yazarı",
    "produksiyon": "Burak Atlas: Prodüktör; Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Pink Limo Entertainment",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "anlattim-ama-anlamadin",
    "baslik": "Anlattım Ama Anlamadın",
    "sanatcilar": "Böyleyken Böyle",
    "album": "Anlattım Ama Anlamadın",
    "albumUrl": "https://open.spotify.com/album/2pz1He98z0MO9RHBnMmGjR",
    "tur": "Single",
    "tarih": "2023-11-17",
    "sure": "3:05",
    "spotifyUrl": "https://open.spotify.com/track/2kQNYcY2fY67niZt3xhMnF",
    "spotifyId": "2kQNYcY2fY67niZt3xhMnF",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273f8b7684d6f12244015d9af9b",
    "sozBeste": "Mustafa Kır: Besteci, Söz Yazarı",
    "produksiyon": "Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "kaldirimlar",
    "baslik": "Kaldırımlar",
    "sanatcilar": "Furkan Kızılay, Alphan Kurtoğlu",
    "album": "Kaldırımlar",
    "albumUrl": "https://open.spotify.com/album/03LlxJQJcF95Uq5vEM8bGf",
    "tur": "Single",
    "tarih": "2023-11-17",
    "sure": "3:27",
    "spotifyUrl": "https://open.spotify.com/track/45WgA7LsG6BduYo4HFi1cU",
    "spotifyId": "45WgA7LsG6BduYo4HFi1cU",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2734494ab5abcdc0d6dc35a61f0",
    "sozBeste": "Furkan Kızılay: Besteci; Alphan Kurtoğlu: Besteci",
    "produksiyon": "Turan Oğuzhan: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "51 Music",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "bombosum",
    "baslik": "Bomboşum",
    "sanatcilar": "Eren Can",
    "album": "Bomboşum",
    "albumUrl": "https://open.spotify.com/album/3jINXVZ68y92WTdKGCEnkk",
    "tur": "Single",
    "tarih": "2023-11-03",
    "sure": "3:28",
    "spotifyUrl": "https://open.spotify.com/track/2JBROCH5Tr9Zv9eBo3BPHA",
    "spotifyId": "2JBROCH5Tr9Zv9eBo3BPHA",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b27363333d6a9bbee1ca978b28be",
    "sozBeste": "Eren Can Erdoğan: Söz Yazarı, Besteci",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "Eren Can Music",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "bir-ileri-bir-geri",
    "baslik": "Bir İleri Bir Geri",
    "sanatcilar": "İVEN",
    "album": "Bir İleri Bir Geri",
    "albumUrl": "https://open.spotify.com/album/1a8E0SewEnLsXbjYjeaxuc",
    "tur": "Single",
    "tarih": "2023-09-08",
    "sure": "3:10",
    "spotifyUrl": "https://open.spotify.com/track/0TixanAcRezYMF7f5bsvHS",
    "spotifyId": "0TixanAcRezYMF7f5bsvHS",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b27301ac17858289bc260f1d2072",
    "sozBeste": "İbrahim İven: Besteci, Söz Yazarı",
    "produksiyon": "İlkay Emre Gökgöz: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Pink Limo Entertainment",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "en-sonunda-terk-ettim-sehrimi",
    "baslik": "En Sonunda Terk Ettim Şehrimi",
    "sanatcilar": "Böyleyken Böyle",
    "album": "En Sonunda Terk Ettim Şehrimi",
    "albumUrl": "https://open.spotify.com/album/49Da5Al1iNGqdjatlyaZTO",
    "tur": "Single",
    "tarih": "2023-08-18",
    "sure": "3:19",
    "spotifyUrl": "https://open.spotify.com/track/5GIisFHTMmJAO497d906SO",
    "spotifyId": "5GIisFHTMmJAO497d906SO",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2733b2a4f9b2024d35517c780f3",
    "sozBeste": "Mustafa Kır: Besteci, Söz Yazarı",
    "produksiyon": "Mustafa Kır: Prodüktör; Muharrem Salcı: Prodüktör; Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "karma",
    "baslik": "KARMA",
    "sanatcilar": "iREM B",
    "album": "KARMA",
    "albumUrl": "https://open.spotify.com/album/0QS2wkr7prj139EMvo1EHn",
    "tur": "Single",
    "tarih": "2023-08-18",
    "sure": "3:05",
    "spotifyUrl": "https://open.spotify.com/track/5oqMAVqTqy9z3sRXQZW55q",
    "spotifyId": "5oqMAVqTqy9z3sRXQZW55q",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273c0aec2c498cf8018aef029e0",
    "sozBeste": "İrem BAYKUT: Söz Yazarı, Besteci",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "iREM B",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "paralel-evren",
    "baslik": "PARALEL EVREN",
    "sanatcilar": "iREM B",
    "album": "PARALEL EVREN",
    "albumUrl": "https://open.spotify.com/album/3JDea7Y5g0kevxNIaGYMbT",
    "tur": "Single",
    "tarih": "2023-07-21",
    "sure": "3:02",
    "spotifyUrl": "https://open.spotify.com/track/39jktOzwaSVUsdRqbMA9sG",
    "spotifyId": "39jktOzwaSVUsdRqbMA9sG",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273abe7c83a4c9f5a1187f95459",
    "sozBeste": "İrem BAYKUT: Söz Yazarı, Besteci",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "iREM B",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "ara",
    "baslik": "Ara",
    "sanatcilar": "Ayda",
    "album": "Ara",
    "albumUrl": "https://open.spotify.com/album/18gvZkGqOFJ7VFsH0sbBXG",
    "tur": "Single",
    "tarih": "2023-06-23",
    "sure": "2:30",
    "spotifyUrl": "https://open.spotify.com/track/1E3HDNrkcA7p2bmh2UXUfQ",
    "spotifyId": "1E3HDNrkcA7p2bmh2UXUfQ",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2735f93270962106cece82d2a28",
    "sozBeste": "Sheyh Ree: Besteci, Söz Yazarı",
    "produksiyon": "Ozade: Prodüktör; Khasbeat: Prodüktör; CanDoe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Two Way",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "deli-gibi-ozleyeceksin",
    "baslik": "Deli Gibi Özleyeceksin",
    "sanatcilar": "Böyleyken Böyle",
    "album": "Deli Gibi Özleyeceksin",
    "albumUrl": "https://open.spotify.com/album/1FQKfyCuDNbEioIRqcQLsL",
    "tur": "Single",
    "tarih": "2023-05-26",
    "sure": "3:15",
    "spotifyUrl": "https://open.spotify.com/track/7rYzT6YWTTt4mImjt0U33a",
    "spotifyId": "7rYzT6YWTTt4mImjt0U33a",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273eb1f87d7f6194919986deddb",
    "sozBeste": "Mustafa Kır: Besteci, Söz Yazarı",
    "produksiyon": "Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "geri-ver",
    "baslik": "geri ver",
    "sanatcilar": "Bulut Atlası",
    "album": "geri ver",
    "albumUrl": "https://open.spotify.com/album/3qTIzMpDWHoetJ3mQzcsGj",
    "tur": "Single",
    "tarih": "2023-05-25",
    "sure": "3:02",
    "spotifyUrl": "https://open.spotify.com/track/2PFRbbF4hhHbUPhYT8yejb",
    "spotifyId": "2PFRbbF4hhHbUPhYT8yejb",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273c9c82ec30076ce7f5b732ece",
    "sozBeste": "Kaan Cengiz: Besteci, Söz Yazarı; Göksel Kadir Yüksel: Besteci; Yusuf Ensar Budak: Besteci",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "yalniz-mum",
    "baslik": "yalnız mum",
    "sanatcilar": "Bulut Atlası",
    "album": "yalnız mum",
    "albumUrl": "https://open.spotify.com/album/3SN6EqtgozHfow6TQ7R4h6",
    "tur": "Single",
    "tarih": "2023-02-03",
    "sure": "3:59",
    "spotifyUrl": "https://open.spotify.com/track/3J6hGpbg3GCKQoST3CMIGJ",
    "spotifyId": "3J6hGpbg3GCKQoST3CMIGJ",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2734ef8b35c99ee0ce1da85f86d",
    "sozBeste": "Kaan Cengiz: Besteci, Söz Yazarı; Göksel Kadir Yüksel: Besteci",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "hep-duserdim-depresyonlara",
    "baslik": "Hep Düşerdim Depresyonlara",
    "sanatcilar": "Böyleyken Böyle",
    "album": "DÖRT BUÇUK",
    "albumUrl": "https://open.spotify.com/album/129H46eD9N9saC9Nta8QJV",
    "tur": "Album",
    "tarih": "2023-01-20",
    "sure": "3:21",
    "spotifyUrl": "https://open.spotify.com/track/3ezIz7ELH4CI0HMfOvtQlT",
    "spotifyId": "3ezIz7ELH4CI0HMfOvtQlT",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2738884992e8272fd678dfe771e",
    "sozBeste": "Mustafa Kır: Besteci, Söz Yazarı",
    "produksiyon": "Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "alistim-uzulmeye",
    "baslik": "Alıştım Üzülmeye",
    "sanatcilar": "Böyleyken Böyle",
    "album": "DÖRT BUÇUK",
    "albumUrl": "https://open.spotify.com/album/129H46eD9N9saC9Nta8QJV",
    "tur": "Album",
    "tarih": "2023-01-20",
    "sure": "3:10",
    "spotifyUrl": "https://open.spotify.com/track/26hb0wz7ohGPSOHLOnants",
    "spotifyId": "26hb0wz7ohGPSOHLOnants",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2738884992e8272fd678dfe771e",
    "sozBeste": "Mustafa Kır: Besteci, Söz Yazarı",
    "produksiyon": "Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "alistim-uzulmeye-2",
    "baslik": "Alıştım Üzülmeye",
    "sanatcilar": "Böyleyken Böyle",
    "album": "Alıştım Üzülmeye",
    "albumUrl": "https://open.spotify.com/album/56RC7UMpMzp4EwKCPZ4xaw",
    "tur": "Single",
    "tarih": "2022-10-14",
    "sure": "3:10",
    "spotifyUrl": "https://open.spotify.com/track/2xFiJX7xL04l2HmwtQVsdm",
    "spotifyId": "2xFiJX7xL04l2HmwtQVsdm",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b27302b7a35bb4c6a02c4b9b6799",
    "sozBeste": "Mustafa Kır: Besteci, Söz Yazarı",
    "produksiyon": "Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "kafamin-icinde",
    "baslik": "Kafamın İçinde",
    "sanatcilar": "The Nashor",
    "album": "Kafamın İçinde",
    "albumUrl": "https://open.spotify.com/album/3OETffQ8g4lamoseYgw6Vf",
    "tur": "Single",
    "tarih": "2022-09-27",
    "sure": "4:48",
    "spotifyUrl": "https://open.spotify.com/track/6mybIBrFSKvtDee5BRC9SR",
    "spotifyId": "6mybIBrFSKvtDee5BRC9SR",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2738fb75ea887967c573a94d86a",
    "sozBeste": null,
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "The Nashor",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "dumanlar-var-uzerimde",
    "baslik": "Dumanlar Var Üzerimde",
    "sanatcilar": "Böyleyken Böyle",
    "album": "Dumanlar Var Üzerimde",
    "albumUrl": "https://open.spotify.com/album/06gMURWEUFTHy8qE2gM3nZ",
    "tur": "Single",
    "tarih": "2022-09-16",
    "sure": "3:34",
    "spotifyUrl": "https://open.spotify.com/track/1OkrkPe2L8afD26lx3nHvL",
    "spotifyId": "1OkrkPe2L8afD26lx3nHvL",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273c659767e3de39fdbb7ae7872",
    "sozBeste": "Mustafa Kır: Besteci, Söz Yazarı",
    "produksiyon": "Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "yerdeyim",
    "baslik": "Yerdeyim",
    "sanatcilar": "Furkan Kızılay, Gönül Filiz",
    "album": "Yerdeyim",
    "albumUrl": "https://open.spotify.com/album/3Snse9H1xQMz42J89HCzgT",
    "tur": "Single",
    "tarih": "2022-09-01",
    "sure": "1:49",
    "spotifyUrl": "https://open.spotify.com/track/2xHSseoH3da5nAgczO6cld",
    "spotifyId": "2xHSseoH3da5nAgczO6cld",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2738ce62fb0c9df5fd0afc212e3",
    "sozBeste": "Oğuzhan Atmaca: Besteci, Söz Yazarı",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "Vibe Global",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "film-gibi",
    "baslik": "Film Gibi",
    "sanatcilar": "Caner Öner",
    "album": "Film Gibi",
    "albumUrl": "https://open.spotify.com/album/3mAC7DX0ciOvmW4hkSu0Bn",
    "tur": "Single",
    "tarih": "2022-08-26",
    "sure": "3:46",
    "spotifyUrl": "https://open.spotify.com/track/3FNVjyslNt6ddqgYd30bdh",
    "spotifyId": "3FNVjyslNt6ddqgYd30bdh",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273c5f1d88bf0764ba711e53705",
    "sozBeste": "Caner Öner: Besteci, Söz Yazarı",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "obsession",
    "baslik": "Obsession",
    "sanatcilar": "Bixi Blake, Kum",
    "album": "Obsession",
    "albumUrl": "https://open.spotify.com/album/0ufgmq1tXqQ5W3wG6oioNl",
    "tur": "Single",
    "tarih": "2022-08-19",
    "sure": "3:20",
    "spotifyUrl": "https://open.spotify.com/track/5jf9Zj1ebsD5gerVZzZ0X4",
    "spotifyId": "5jf9Zj1ebsD5gerVZzZ0X4",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2734d3a235922c8c6a377fd1657",
    "sozBeste": "Emin Arslan: Besteci, Söz Yazarı; Burkut Kum: Söz Yazarı",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "Hypers",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "sabahin-dort-bucugunda",
    "baslik": "Sabahın Dört Buçuğunda",
    "sanatcilar": "Böyleyken Böyle",
    "album": "Sabahın Dört Buçuğunda",
    "albumUrl": "https://open.spotify.com/album/5aKXt3i7tNjPHlbJLvaL5y",
    "tur": "Single",
    "tarih": "2022-08-12",
    "sure": "3:37",
    "spotifyUrl": "https://open.spotify.com/track/5ps4DiaUpc6l96ixypIXkn",
    "spotifyId": "5ps4DiaUpc6l96ixypIXkn",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273e54680d8a54825250f74c831",
    "sozBeste": "Mustafa Kır: Besteci, Söz Yazarı",
    "produksiyon": "Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "eksik",
    "baslik": "eksik",
    "sanatcilar": "Bulut Atlası",
    "album": "eksik",
    "albumUrl": "https://open.spotify.com/album/1pF8uItJ8RzX9FXfb9LfMF",
    "tur": "Single",
    "tarih": "2022-08-12",
    "sure": "3:59",
    "spotifyUrl": "https://open.spotify.com/track/3PzbUhBM3E6fg5pO2bVsYG",
    "spotifyId": "3PzbUhBM3E6fg5pO2bVsYG",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273a3d39d3bcca1b5b0319aa3b8",
    "sozBeste": "Kaan Cengiz: Söz Yazarı, Besteci; Kadir Yüksel: Besteci",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "Bulut Atlası",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "senden-sonra",
    "baslik": "Senden Sonra",
    "sanatcilar": "Caner Öner",
    "album": "Senden Sonra",
    "albumUrl": "https://open.spotify.com/album/0pBUNBlZy7JhVyD3xxMZoM",
    "tur": "Single",
    "tarih": "2022-07-22",
    "sure": "3:56",
    "spotifyUrl": "https://open.spotify.com/track/6SZ3yJnBTblz1H3wy1fiMm",
    "spotifyId": "6SZ3yJnBTblz1H3wy1fiMm",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b27362a4da3ed2976d223cdeba70",
    "sozBeste": "Caner Öner: Besteci, Söz Yazarı",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "yolu-bitti",
    "baslik": "Yolu Bitti",
    "sanatcilar": "Caner Öner, Nihan Doğa",
    "album": "Yolu Bitti",
    "albumUrl": "https://open.spotify.com/album/0vmk64NgRwX8MRhodQ5UNw",
    "tur": "Single",
    "tarih": "2022-06-24",
    "sure": "3:42",
    "spotifyUrl": "https://open.spotify.com/track/4Eild2yen2paQsQCKmKvZX",
    "spotifyId": "4Eild2yen2paQsQCKmKvZX",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2735235b5d9c627ad0df5a0c88d",
    "sozBeste": "Caner Öner: Besteci, Söz Yazarı",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "mutemadiyen",
    "baslik": "Mütemadiyen",
    "sanatcilar": "Furkan Kızılay",
    "album": "Mütemadiyen",
    "albumUrl": "https://open.spotify.com/album/7MSx4M7FxTM2UinKoeGXHf",
    "tur": "Single",
    "tarih": "2022-06-10",
    "sure": "2:25",
    "spotifyUrl": "https://open.spotify.com/track/0yeCkdVYxTUdQ6HaTsqTZY",
    "spotifyId": "0yeCkdVYxTUdQ6HaTsqTZY",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b27350c8a6b368210f15cf9650ea",
    "sozBeste": "Yiğitcan Kiremitçi: Besteci, Söz Yazarı",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Besteci",
      "Söz Yazarı"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "gorur-gormez",
    "baslik": "Görür Görmez",
    "sanatcilar": "Olabilir!",
    "album": "Görür Görmez",
    "albumUrl": "https://open.spotify.com/album/2y960ScCZGMg3vhEVKmdzp",
    "tur": "Single",
    "tarih": "2022-06-07",
    "sure": "3:05",
    "spotifyUrl": "https://open.spotify.com/track/7bcSr0rUNWA4o7PaUS68Sq",
    "spotifyId": "7bcSr0rUNWA4o7PaUS68Sq",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273a435ff2f88b65081254e0855",
    "sozBeste": "Can Berk Genceroğlu: Söz Yazarı, Besteci",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "3933929 Records DK2",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "kirmizi-vosvos",
    "baslik": "Kırmızı Vosvos",
    "sanatcilar": "Böyleyken Böyle",
    "album": "Kırmızı Vosvos",
    "albumUrl": "https://open.spotify.com/album/1g6uUtIoTEiv28t6laEnLC",
    "tur": "Single",
    "tarih": "2022-06-03",
    "sure": "3:02",
    "spotifyUrl": "https://open.spotify.com/track/2ENvruWpQW39J1uvllWjXr",
    "spotifyId": "2ENvruWpQW39J1uvllWjXr",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273f14483b051ee697e7a519127",
    "sozBeste": "Mustafa Kır: Besteci, Söz Yazarı",
    "produksiyon": "Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "son-kadehler-kalkti",
    "baslik": "Son Kadehler Kalktı",
    "sanatcilar": "Caner Öner",
    "album": "Son Kadehler Kalktı",
    "albumUrl": "https://open.spotify.com/album/2HrYyMXUCXsf2uVZYm1B5m",
    "tur": "Single",
    "tarih": "2022-05-27",
    "sure": "4:44",
    "spotifyUrl": "https://open.spotify.com/track/09XdTTkccEcbkBEuQqUr4e",
    "spotifyId": "09XdTTkccEcbkBEuQqUr4e",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273b5c1d60585ae55978ade99a6",
    "sozBeste": "Caner Öner: Besteci, Söz Yazarı",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "bana-ask-yok-mu",
    "baslik": "bana aşk yok mu",
    "sanatcilar": "Bulut Atlası",
    "album": "bana aşk yok mu",
    "albumUrl": "https://open.spotify.com/album/0Uby5GILVTIA2gYmWtXYx9",
    "tur": "Single",
    "tarih": "2022-05-20",
    "sure": "4:01",
    "spotifyUrl": "https://open.spotify.com/track/6YSDW5vQrV6X9jPFlkRYGV",
    "spotifyId": "6YSDW5vQrV6X9jPFlkRYGV",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273e61f55066eb9465abe036523",
    "sozBeste": "Kaan Cengiz: Besteci, Söz Yazarı; Göksel Kadir Yüksel: Besteci",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "DMC",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "deli-gibi-ozledim",
    "baslik": "Deli Gibi Özledim",
    "sanatcilar": "Böyleyken Böyle",
    "album": "Deli Gibi Özledim",
    "albumUrl": "https://open.spotify.com/album/42AIybyAjUmPA5k2dpBROW",
    "tur": "Single",
    "tarih": "2022-05-13",
    "sure": "3:55",
    "spotifyUrl": "https://open.spotify.com/track/4fkBt4R5wnHiHLKFdXhFgf",
    "spotifyId": "4fkBt4R5wnHiHLKFdXhFgf",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2731901880012a06f831002982b",
    "sozBeste": "Mustafa Kır: Besteci, Söz Yazarı",
    "produksiyon": "Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "daha-derine",
    "baslik": "Daha Derine",
    "sanatcilar": "Bixi Blake",
    "album": "Daha Derine",
    "albumUrl": "https://open.spotify.com/album/2tBFYNrsVMADLP2SUE70Fh",
    "tur": "Single",
    "tarih": "2022-05-06",
    "sure": "2:44",
    "spotifyUrl": "https://open.spotify.com/track/0y8976efiDyFxENxeLCVJB",
    "spotifyId": "0y8976efiDyFxENxeLCVJB",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b27381714b710f0039586f4a7abb",
    "sozBeste": "Emin Arslan: Besteci, Söz Yazarı; Emirhan Ermenek: Besteci; Mehmet Salih Kuzal: Besteci",
    "produksiyon": "Bixi Blake: Prodüktör; Yvng Demo: Prodüktör; Nightvision: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Hypers",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "unfazed",
    "baslik": "Unfazed",
    "sanatcilar": "Samar in Silence",
    "album": "Unfazed",
    "albumUrl": "https://open.spotify.com/album/39T3XChzw18BWv4x99c0EQ",
    "tur": "Single",
    "tarih": "2022-04-29",
    "sure": "3:26",
    "spotifyUrl": "https://open.spotify.com/track/1KuxcIjvfEw5PVGK5iNtgA",
    "spotifyId": "1KuxcIjvfEw5PVGK5iNtgA",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2730336aa108675f358a7998c38",
    "sozBeste": "Samar Halim: Söz Yazarı, Besteci",
    "produksiyon": "Samar Halim: Stüdyo Prodüktörü",
    "digerKunye": null,
    "kunyeKaynagi": "Silence Records",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "kirmizi",
    "baslik": "Kırmızı",
    "sanatcilar": "Furkan Kızılay",
    "album": "Kırmızı",
    "albumUrl": "https://open.spotify.com/album/0fStLirdl3onRUhCQEJvZE",
    "tur": "Single",
    "tarih": "2022-04-22",
    "sure": "2:56",
    "spotifyUrl": "https://open.spotify.com/track/4qbWO39xCOUfH0f79siE0H",
    "spotifyId": "4qbWO39xCOUfH0f79siE0H",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2737cd9cb1b6489885d31fd057b",
    "sozBeste": "Yiğitcan Kiremitçi: Besteci, Söz Yazarı",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Besteci",
      "Söz Yazarı"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "yara-aldim",
    "baslik": "Yara Aldım",
    "sanatcilar": "Böyleyken Böyle",
    "album": "Yara Aldım",
    "albumUrl": "https://open.spotify.com/album/0a3pkorOZiwvdxxcSl96ja",
    "tur": "Single",
    "tarih": "2022-04-22",
    "sure": "3:03",
    "spotifyUrl": "https://open.spotify.com/track/4P8CK6rQv1N52WNSkjgR8q",
    "spotifyId": "4P8CK6rQv1N52WNSkjgR8q",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273c25067f3700a7403270c12db",
    "sozBeste": "Mustafa Kır: Besteci, Söz Yazarı, Aranjör; Can Doe: Aranjör; Muharrem Salcı: Aranjör",
    "produksiyon": "Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Aranjör",
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "hepsi-sen-ve-ben",
    "baslik": "hepsi sen ve ben",
    "sanatcilar": "Bulut Atlası",
    "album": "hepsi sen ve ben",
    "albumUrl": "https://open.spotify.com/album/35gzDj84entJFsiXSZbgvH",
    "tur": "Single",
    "tarih": "2022-04-08",
    "sure": "3:33",
    "spotifyUrl": "https://open.spotify.com/track/5smU9yNqndLtk1SZua2SBk",
    "spotifyId": "5smU9yNqndLtk1SZua2SBk",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273b9952bd66be5f1daaa6c1276",
    "sozBeste": "Kaan Cengiz: Besteci, Söz Yazarı, Aranjör; Göksel Kadir Yüksel: Besteci, Aranjör",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "DMC",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "al-beni-bas-yaralarina",
    "baslik": "Al Beni Bas Yaralarına",
    "sanatcilar": "İkiye On Kala",
    "album": "Al Beni Bas Yaralarına",
    "albumUrl": "https://open.spotify.com/album/2hGCjMExwVRdJq5kFuTBxF",
    "tur": "Single",
    "tarih": "2022-03-25",
    "sure": "2:48",
    "spotifyUrl": "https://open.spotify.com/track/4GBc3jN4IGnoCW97YWvdoI",
    "spotifyId": "4GBc3jN4IGnoCW97YWvdoI",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273cb47a72314c47d20711df62c",
    "sozBeste": "Uğur Uras Ustaoğlu: Besteci, Söz Yazarı",
    "produksiyon": "Uğur Uras Ustaoğlu: Prodüktör; Furkan Yekta Özgenç: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Joojee",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "beklemem-ondan",
    "baslik": "Beklemem Ondan",
    "sanatcilar": "Furkan Kızılay",
    "album": "Beklemem Ondan",
    "albumUrl": "https://open.spotify.com/album/08T7bxliGo63mpYBchyehs",
    "tur": "Single",
    "tarih": "2022-03-25",
    "sure": "2:47",
    "spotifyUrl": "https://open.spotify.com/track/1dovjjWBiGWmEL7Fv2GuOF",
    "spotifyId": "1dovjjWBiGWmEL7Fv2GuOF",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2737a679a31382b91033fb1639f",
    "sozBeste": "Yiğitcan Kiremitçi: Besteci, Söz Yazarı, Aranjör",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Besteci",
      "Söz Yazarı",
      "Aranjör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "ne-kadar-uzagim",
    "baslik": "Ne Kadar Uzağım",
    "sanatcilar": "Soft Analog",
    "album": "Ne Kadar Uzağım",
    "albumUrl": "https://open.spotify.com/album/4QEIx8fZy2dMewCZ6PklO7",
    "tur": "Single",
    "tarih": "2022-03-18",
    "sure": "3:24",
    "spotifyUrl": "https://open.spotify.com/track/0AsCRM37KbwUOxE4e2My7u",
    "spotifyId": "0AsCRM37KbwUOxE4e2My7u",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2737947ba32a6c106f7ce1a8c35",
    "sozBeste": "İdil Tavşanlı: Besteci; Ömer Çelik: Besteci",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "Apartment Disco",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "niye-benle-savastin",
    "baslik": "Niye Benle Savaştın",
    "sanatcilar": "Böyleyken Böyle",
    "album": "Niye Benle Savaştın",
    "albumUrl": "https://open.spotify.com/album/1IYOJXmyOCAeWXDQYmQVwK",
    "tur": "Single",
    "tarih": "2022-03-18",
    "sure": "3:21",
    "spotifyUrl": "https://open.spotify.com/track/4o004de5sLBuR1Kio9ToPB",
    "spotifyId": "4o004de5sLBuR1Kio9ToPB",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b27384b59f1fb1c275a468e7acb4",
    "sozBeste": "Mustafa Kır: Besteci, Söz Yazarı, Aranjör; Yiğitcan Kiremitçi: Aranjör; Muharrem Salcı: Aranjör",
    "produksiyon": "Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Aranjör",
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "depresyon-guzelim",
    "baslik": "Depresyon Güzelim",
    "sanatcilar": "İkiye On Kala",
    "album": "Depresyon Güzelim",
    "albumUrl": "https://open.spotify.com/album/06MJkFyLd0bhs6v0OFz9nI",
    "tur": "Single",
    "tarih": "2022-02-25",
    "sure": "2:41",
    "spotifyUrl": "https://open.spotify.com/track/6yxIrN4Jj3uWI6hMhC1bac",
    "spotifyId": "6yxIrN4Jj3uWI6hMhC1bac",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273925dde2cfa6ec51c4264e7c9",
    "sozBeste": "Uğur Uras Ustaoğlu: Besteci, Söz Yazarı",
    "produksiyon": "Uğur Uras Ustaoğlu: Prodüktör; Furkan Yekta Özgenç: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Joojee",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "firtina",
    "baslik": "Fırtına",
    "sanatcilar": "Furkan Kızılay",
    "album": "Fırtına",
    "albumUrl": "https://open.spotify.com/album/0zMhhPkqhHn9Zym3oGdGiJ",
    "tur": "Single",
    "tarih": "2022-02-25",
    "sure": "3:39",
    "spotifyUrl": "https://open.spotify.com/track/4yFpXnBAycyxVYRvPak4Nx",
    "spotifyId": "4yFpXnBAycyxVYRvPak4Nx",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2734778b47ef261e5c14513ced3",
    "sozBeste": "Yiğitcan Kiremitçi: Besteci, Söz Yazarı; Can Doe: Aranjör",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Besteci",
      "Söz Yazarı",
      "Aranjör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "kalbinde-lunapark",
    "baslik": "Kalbinde Lunapark",
    "sanatcilar": "İkiye On Kala",
    "album": "Kalbinde Lunapark",
    "albumUrl": "https://open.spotify.com/album/59lQbxMsDVuXRNNr4ZMoZX",
    "tur": "Single",
    "tarih": "2022-02-11",
    "sure": "2:34",
    "spotifyUrl": "https://open.spotify.com/track/3fevNLGvjPEjMzS8v8wwLZ",
    "spotifyId": "3fevNLGvjPEjMzS8v8wwLZ",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273245e2db810231268c1b0182d",
    "sozBeste": "Uğur Uras Ustaoğlu: Besteci, Söz Yazarı",
    "produksiyon": "Uğur Uras Ustaoğlu: Prodüktör; Furkan Yekta Özgenç: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Joojee",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "anne-ben",
    "baslik": "Anne Ben",
    "sanatcilar": "İkiye On Kala",
    "album": "Anne Ben",
    "albumUrl": "https://open.spotify.com/album/6TtlgQvDifbAxeO6WUztMg",
    "tur": "Single",
    "tarih": "2022-01-28",
    "sure": "2:22",
    "spotifyUrl": "https://open.spotify.com/track/4abo86SrlMSYq0Mxy7Qisw",
    "spotifyId": "4abo86SrlMSYq0Mxy7Qisw",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b27333ddabead5f74cd8b88f9f3f",
    "sozBeste": "Uğur Uras Ustaoğlu: Besteci, Söz Yazarı",
    "produksiyon": "Uğur Uras Ustaoğlu: Prodüktör; Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Joojee",
    "roller": [
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "istanbul",
    "baslik": "İstanbul",
    "sanatcilar": "Furkan Kızılay",
    "album": "İstanbul",
    "albumUrl": "https://open.spotify.com/album/7cFaJzC73YvGBiWr92kmap",
    "tur": "Single",
    "tarih": "2022-01-28",
    "sure": "3:27",
    "spotifyUrl": "https://open.spotify.com/track/3tmyhqzH7VFtMFzDb3TkfA",
    "spotifyId": "3tmyhqzH7VFtMFzDb3TkfA",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b27324f76ed05b1f2f29f631b384",
    "sozBeste": "Can Doe: Besteci, Söz Yazarı, Aranjör",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "GARAJ",
    "roller": [
      "Besteci",
      "Söz Yazarı",
      "Aranjör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "derin",
    "baslik": "Derin",
    "sanatcilar": "İkiye On Kala",
    "album": "Derin",
    "albumUrl": "https://open.spotify.com/album/1xDluR743tUFdPUTUNFLuN",
    "tur": "Single",
    "tarih": "2022-01-14",
    "sure": "2:47",
    "spotifyUrl": "https://open.spotify.com/track/4gmr6Qfgkgt0lZ1rJEjDTX",
    "spotifyId": "4gmr6Qfgkgt0lZ1rJEjDTX",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273a710e38ffea6136a43635eec",
    "sozBeste": "Uğur Uras Ustaoğlu: Besteci, Söz Yazarı",
    "produksiyon": "Uğur Uras Ustaoğlu: Prodüktör; Furkan Yekta Özgenç: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Joojee",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "beni-cek",
    "baslik": "Beni Çek",
    "sanatcilar": "İkiye On Kala",
    "album": "Beni Çek",
    "albumUrl": "https://open.spotify.com/album/2uwq3VDLWubO9BWh2KA3EK",
    "tur": "Single",
    "tarih": "2021-12-24",
    "sure": "3:07",
    "spotifyUrl": "https://open.spotify.com/track/6uns3tmutyWVLjGqijSIRY",
    "spotifyId": "6uns3tmutyWVLjGqijSIRY",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273f411fe6e4d5cfd7fd72cb61a",
    "sozBeste": "Uğur Uras Ustaoğlu: Besteci, Söz Yazarı",
    "produksiyon": "Uğur Uras Ustaoğlu: Prodüktör; Furkan Yekta Özgenç: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Joojee",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "cok-goc-aldim-suriye-den",
    "baslik": "Çok Göç Aldım Suriye'den",
    "sanatcilar": "İkiye On Kala",
    "album": "Çok Göç Aldım Suriye'den",
    "albumUrl": "https://open.spotify.com/album/7sZqHTZVbHOpThSAWNFXam",
    "tur": "Single",
    "tarih": "2021-12-17",
    "sure": "2:34",
    "spotifyUrl": "https://open.spotify.com/track/4Bhihc4uaqoD7MzXxy9tM0",
    "spotifyId": "4Bhihc4uaqoD7MzXxy9tM0",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2732df59e19d0c598bcdf1cce19",
    "sozBeste": "Uğur Uras Ustaoğlu: Besteci, Söz Yazarı",
    "produksiyon": "Uğur Uras Ustaoğlu: Prodüktör; Furkan Yekta Özgenç: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Joojee",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "bombalar",
    "baslik": "Bombalar",
    "sanatcilar": "Soft Analog",
    "album": "Bombalar",
    "albumUrl": "https://open.spotify.com/album/6OtOYYi6hjTHZaCaobG3VJ",
    "tur": "Single",
    "tarih": "2021-12-10",
    "sure": "4:23",
    "spotifyUrl": "https://open.spotify.com/track/26aBwDb2Lge4uS8NfEUK71",
    "spotifyId": "26aBwDb2Lge4uS8NfEUK71",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b27365afb737b695dc38359b906e",
    "sozBeste": "İdil Tavşanlı: Besteci; Ömer Çelik: Besteci",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "Morrie Records",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "all-i-know",
    "baslik": "All I Know",
    "sanatcilar": "Samar in Silence",
    "album": "All I Know",
    "albumUrl": "https://open.spotify.com/album/0EiH8PeWkIREk8VRPmnTsd",
    "tur": "Single",
    "tarih": "2021-10-22",
    "sure": "3:19",
    "spotifyUrl": "https://open.spotify.com/track/26kwwiJFI6045HHvvkAyWO",
    "spotifyId": "26kwwiJFI6045HHvvkAyWO",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273e02b5a59a6b7f62a0d3700b1",
    "sozBeste": "Samar Halim: Söz Yazarı, Besteci",
    "produksiyon": "Samar Halim: Stüdyo Prodüktörü",
    "digerKunye": null,
    "kunyeKaynagi": "Silence Records",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "adalarin-karsisi",
    "baslik": "Adaların Karşısı",
    "sanatcilar": "Yaren Arduçluoğlu",
    "album": "Adaların Karşısı",
    "albumUrl": "https://open.spotify.com/album/0Qxka4FhG5nLClBMMKQDuc",
    "tur": "Single",
    "tarih": "2021-05-18",
    "sure": "3:34",
    "spotifyUrl": "https://open.spotify.com/track/0rXaEpUg0zcrvR0II58c8h",
    "spotifyId": "0rXaEpUg0zcrvR0II58c8h",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273598bb0fbb7c0c33fc94675b0",
    "sozBeste": "Yaren Arduçluoğlu: Besteci; Berkay Eren: Besteci",
    "produksiyon": "Berkay Eren: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "PYST by Gazel Müzik",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "soluk-soluga",
    "baslik": "Soluk Soluğa",
    "sanatcilar": "Burak Gözen",
    "album": "Soluk Soluğa",
    "albumUrl": "https://open.spotify.com/album/197lbyozUCd8KDOXvIOGgb",
    "tur": "Single",
    "tarih": "2021-04-30",
    "sure": "3:35",
    "spotifyUrl": "https://open.spotify.com/track/5rGtaGukQ1Wo30meTwd2OJ",
    "spotifyId": "5rGtaGukQ1Wo30meTwd2OJ",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273704d16ad16ebecb5e062dacd",
    "sozBeste": "Burak Gözen: Besteci; Yiğit Can Kiremitci: Besteci",
    "produksiyon": "Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "PYST by Gazel Müzik",
    "roller": [
      "Besteci",
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "senin-olamam",
    "baslik": "Senin Olamam",
    "sanatcilar": "Can Doe",
    "album": "Senin Olamam",
    "albumUrl": "https://open.spotify.com/album/3QMymMhrfv1RcXg0TnlPCh",
    "tur": "Single",
    "tarih": "2021-02-26",
    "sure": "4:04",
    "spotifyUrl": "https://open.spotify.com/track/1y0tAAwiVHD4h5Oxfdi8aP",
    "spotifyId": "1y0tAAwiVHD4h5Oxfdi8aP",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273387d20f3ac3fe1cfeb2f3edb",
    "sozBeste": "Yiğit Can Kiremitci: Besteci",
    "produksiyon": "Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "PYST",
    "roller": [
      "Besteci",
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "son-durak",
    "baslik": "Son Durak",
    "sanatcilar": "Yaren Arduçluoğlu",
    "album": "Son Durak",
    "albumUrl": "https://open.spotify.com/album/0FKhiVXN4kxwNPFL3nDHd5",
    "tur": "Single",
    "tarih": "2021-01-21",
    "sure": "2:52",
    "spotifyUrl": "https://open.spotify.com/track/3vm6UTXPSUKV3e2lJ0tpQI",
    "spotifyId": "3vm6UTXPSUKV3e2lJ0tpQI",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2738e04db0d7a73f010a0d9ab59",
    "sozBeste": "Yaren Arduçluoğlu: Besteci",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "PYST",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "sikildim",
    "baslik": "Sıkıldım",
    "sanatcilar": "Furkan Kızılay, Can Doe",
    "album": "Sıkıldım",
    "albumUrl": "https://open.spotify.com/album/5TlDWG0hW9mXFTGCKJs81M",
    "tur": "Single",
    "tarih": "2021-01-15",
    "sure": "2:42",
    "spotifyUrl": "https://open.spotify.com/track/6qlEiRUDfgBdc0Wig8LaO4",
    "spotifyId": "6qlEiRUDfgBdc0Wig8LaO4",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273a8909d84f66c8ac3200eaad9",
    "sozBeste": "Yiğit Can Kiremitci: Besteci",
    "produksiyon": "Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "PYST",
    "roller": [
      "Besteci",
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "yillar-gecmis",
    "baslik": "Yıllar Geçmiş",
    "sanatcilar": "Böyleyken Böyle",
    "album": "Yıllar Geçmiş",
    "albumUrl": "https://open.spotify.com/album/67JvBbVYxLJhnZtmeYLQsY",
    "tur": "Single",
    "tarih": "2021-01-08",
    "sure": "3:06",
    "spotifyUrl": "https://open.spotify.com/track/3h1mfcKwM1CUP2UHjMpoDe",
    "spotifyId": "3h1mfcKwM1CUP2UHjMpoDe",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273851c14843c533d60c5a3783b",
    "sozBeste": "Mustafa Kır: Söz Yazarı, Besteci",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "Böyleyken Böyle",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "kafama-gore",
    "baslik": "Kafama Göre",
    "sanatcilar": "Barlascea",
    "album": "Kafama Göre",
    "albumUrl": "https://open.spotify.com/album/13HjrMQOGr6l5dwMMEnwFa",
    "tur": "Single",
    "tarih": "2020-10-02",
    "sure": "3:14",
    "spotifyUrl": "https://open.spotify.com/track/1HJouh4LSF2kwwwABbHIy6",
    "spotifyId": "1HJouh4LSF2kwwwABbHIy6",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273d81a5d96b61249277c7f2aea",
    "sozBeste": "Barış Uysal: Söz Yazarı, Besteci",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "ceamüzik",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "yuruyorum-karanliga-dogru",
    "baslik": "Yürüyorum Karanlığa Doğru",
    "sanatcilar": "Özkan Sağın",
    "album": "Yürüyorum Karanlığa Doğru",
    "albumUrl": "https://open.spotify.com/album/2XY8m00lfjjAsfRdTSgU2T",
    "tur": "Single",
    "tarih": "2020-09-10",
    "sure": "3:14",
    "spotifyUrl": "https://open.spotify.com/track/5YkUqXh3itKRifM39a3mgR",
    "spotifyId": "5YkUqXh3itKRifM39a3mgR",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273929634c8bba4c74068f977ff",
    "sozBeste": "Özkan Sağın: Besteci; Can Kiremitci: Besteci",
    "produksiyon": "Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "Özkan Sağın",
    "roller": [
      "Besteci",
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "gamble-bingo",
    "baslik": "Gamble Bingo",
    "sanatcilar": "Yiğit Taşcılar, SipHoo",
    "album": "Gamble Bingo",
    "albumUrl": "https://open.spotify.com/album/22gT87yXxfEeV900olZw6h",
    "tur": "Single",
    "tarih": "2020-09-04",
    "sure": "2:41",
    "spotifyUrl": "https://open.spotify.com/track/2ZxZNJSbyzA393w8vlmalW",
    "spotifyId": "2ZxZNJSbyzA393w8vlmalW",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b27340c6481b94e4c7cb0498bef1",
    "sozBeste": "Mert Pilge: Söz Yazarı; Yiğit Taşcılar: Söz Yazarı",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "Epidemik Yapım",
    "roller": [],
    "kategori": "miks"
  },
  {
    "slug": "o-da-bendim",
    "baslik": "O da Bendim",
    "sanatcilar": "Böyleyken Böyle",
    "album": "O da Bendim",
    "albumUrl": "https://open.spotify.com/album/6JFYnyzd4kesx5mpOOiKc9",
    "tur": "Single",
    "tarih": "2020-08-19",
    "sure": "4:28",
    "spotifyUrl": "https://open.spotify.com/track/6eO7sUUPhQs2ak0IH0QXA4",
    "spotifyId": "6eO7sUUPhQs2ak0IH0QXA4",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273ba8cddceb1e0af7b5069c10b",
    "sozBeste": "Mustafa Kır: Söz Yazarı, Besteci; Can Doe: Aranjör",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "Djital Meydan",
    "roller": [
      "Aranjör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "alsam-seni",
    "baslik": "Alsam Seni",
    "sanatcilar": "Can Doe, Furkan Kızılay",
    "album": "Alsam Seni",
    "albumUrl": "https://open.spotify.com/album/63Db65Ce2WsXDaVySXhEB6",
    "tur": "Single",
    "tarih": "2020-08-05",
    "sure": "2:27",
    "spotifyUrl": "https://open.spotify.com/track/6LYcGCRYkdJ4nMMs6wzPw6",
    "spotifyId": "6LYcGCRYkdJ4nMMs6wzPw6",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b2739ece22edbdc7215181247f5c",
    "sozBeste": "Atılay Kebapcıoğlu: Besteci; Yiğit Can Kiremitci: Besteci",
    "produksiyon": "Can Doe: Prodüktör",
    "digerKunye": null,
    "kunyeKaynagi": "PYST",
    "roller": [
      "Besteci",
      "Prodüktör"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "yoyo",
    "baslik": "YoYo",
    "sanatcilar": "SipHoo",
    "album": "YoYo",
    "albumUrl": "https://open.spotify.com/album/1BRqqd0UJwWcx30Az1bv5T",
    "tur": "Single",
    "tarih": "2020-05-26",
    "sure": "2:44",
    "spotifyUrl": "https://open.spotify.com/track/6kEjqFog7AiSmAn9aPcBAV",
    "spotifyId": "6kEjqFog7AiSmAn9aPcBAV",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273e2ba5dfff50c15d28619a6fc",
    "sozBeste": "Mert Pilge: Söz Yazarı; Can Kiremitci: Besteci",
    "produksiyon": "Burak Demirörs: Vokal Mühendisi; Garage Underground: Stüdyo Personeli",
    "digerKunye": "Aykut Dank: Grafik Tasarımcı",
    "kunyeKaynagi": "GarageUnderground",
    "roller": [
      "Besteci"
    ],
    "kategori": "muzik"
  },
  {
    "slug": "kendime-not",
    "baslik": "Kendime Not",
    "sanatcilar": "Can Doe",
    "album": "Kendime Not",
    "albumUrl": "https://open.spotify.com/album/1LhHWKKsY2BQpnZ5pVIQ18",
    "tur": "Single",
    "tarih": "2019-11-29",
    "sure": "3:15",
    "spotifyUrl": "https://open.spotify.com/track/7B8JhVXBE1gGRRgnYKsU4M",
    "spotifyId": "7B8JhVXBE1gGRRgnYKsU4M",
    "appleUrl": null,
    "kapak": "https://i.scdn.co/image/ab67616d0000b273d3cc07d95569868193d954e6",
    "sozBeste": "Can Kiremitci: Söz Yazarı",
    "produksiyon": null,
    "digerKunye": null,
    "kunyeKaynagi": "Epidemik Yapım",
    "roller": [
      "Söz Yazarı"
    ],
    "kategori": "muzik"
  }
];
